const PARTICIPANT_TOKEN_DURATION_IN_MINUTES = 20160; // 14 days (max)

const CHAT_TOKEN_SESSION_DURATION_IN_MINUTES = 180; // 3 hours (max)

const RESOURCE_TAGS = { stack: process.env.STACK as string };

export {
  CHAT_TOKEN_SESSION_DURATION_IN_MINUTES,
  PARTICIPANT_TOKEN_DURATION_IN_MINUTES,
  RESOURCE_TAGS
};
